### PR TITLE
feat: create an unprivileged user

### PR DESCRIPTION
**Pull request by Midnighter**
(Alternative title: officially condone the DD-DeCaF giraffe.)

An unprivileged user is big security feature since there are no known
container break-outs with non-root users. Additionally, building the
image will inject your own UID and GID thus when mounting your code
directory, files created by the docker user will belong to you on the
host system.

### CODE REVIEW

**Comment by kvikshaug** [comment]
Unfortunately, this fails with the ids on my mac (`1815517416:848276677`).

```
addgroup: number 848276677 is not in 0..256000 range
```

I don't yet know exactly where the large numbers come from (although likely somehow related to active directory), and if it is something that can/should be fixed on my end.

**Comment by Midnighter** [comment]
Yikes, not sure what to do about that. I wonder how Mac OS does it since it's also UNIX-based...

**Comment by Midnighter** [comment]
:cry: it was a short but glorious life giraffe.

**Comment by kvikshaug** [comment]
RIP

```

        (\-/)
       (:O O:)
        \   /o\
         | |\o \  
         (:) \ o\  
              \o \--_ 
              ( o O
              (  O
```

**Pull request closed without merging**
