### PR TITLE
feat: add installation via `setup.py`

### LINKED ISSUE #2: README should be .rst and needs some TLC

### LINKED ISSUE #3: Package installation
setup.py, setup.cfg, versioneer, pyproject.toml, affects Docker as well

### PR DESCRIPTION
**Pull request by Midnighter**
* fix #3 
* partially fix #2 

@DD-DeCaF/dev making our services installable via `setup.py` and therefore tracking the services' dependencies in `install_requires` may be a contentious move but I believe it doesn't have negative consequences now while potentially letting us distribute our services via PyPi in future.

TODO: Adapt `Makefile`, `tox.ini`, and `.travis.yml` in another PR.

### CODE REVIEW

**Comment by Midnighter** [comment]
> How does this change the package management workflow? Are new packages still installed with pipenv? Will the lock mechanisms work like before?

This way, new dependencies would be added to the `setup.cfg` file. New development requirements would still be added by running `pipenv install --dev xyz` and end up in the `Pipfile`. By installing the tool via `pipenv install .` everything would end up in the `Pipfile.lock`.

> How does versioneer affect the workflow? What does it provide? Can't we just manually add git tag and update a version string, or create a small script for that?

The nice thing about versioneer is that it uses the most recent git tag for creating the version information.  So you simply tag a certain commit and you're done. No need to run a script afterwards to modify versions.

**Comment by kvikshaug** [comment]
> This way, new dependencies would be added to the `setup.cfg` file. New development requirements would still be added by running `pipenv install --dev xyz` and end up in the `Pipfile`. By installing the tool via `pipenv install .` everything would end up in the `Pipfile.lock`.

So we get two different ways of adding packages. Not the end of the world, but I don't see the benefit of the potential to release our packages, in my mind our services are part of a tightly integrated web platform that simply acts as a friendly interface to packages that do make sense to release.

> The nice thing about versioneer is that it uses the most recent git tag for creating the version information.  So you simply tag a certain commit and you're done. No need to run a script afterwards to modify versions.

So this requires us to add the git repo and a git library in all our deployments, in order to have the version number available at runtime? That can easily be achieved with a CI script which reads the latest tag to a version file which the app reads on startup -- if the `__version__` is even needed in the application at all.

Side note: When I run `versioneer install`, it actually takes the liberty to add the newly created files to my local git index. I strongly dislike that, and see it not as a big problem in itself, but a sign that the developers overstep boundaries and makes me distrust the library.

**Comment by Midnighter** [comment]
Okay, I'll take that part out. It really just seems to over-complicate things. What's your suggestion for versioning then? Because I do thing we should version our services/docker images. Bumpversion works sort of but hasn't been maintained in a while.

**Comment by kvikshaug** [comment]
Well, what exactly do we want to accomplish by versioning the services? For example, as opposed to just versioning the APIs. If it's about controlling deployments, maybe blue/green deploys and even [rainbow deploys](http://brandon.dimcheff.com/2018/02/rainbow-deploys-with-kubernetes/) might be worth looking into.

**Comment by Midnighter** [comment]
I was thinking more in terms of semantic versioning of our images/services. To me, a major version change is a new API version. However, we make plenty of changes to the services internally that do not change the API. So when a problem comes up it'd be nice to know this is happening in `x.y.z` but was fine in `k.l.m.`. Of course, we do use git commit hashes to tag our images but once we move to configured deploys I imagine it to be easier to say I want services with the following versions rather than copying in commit hashes.

This discussion doesn't affect whether dependencies should be declared in the `Pipfile` or `setup.cfg`, though, so I have no problem reverting that.

**Comment by Midnighter** [comment]
Alright, conclusion from offline discussion with @kvikshaug: Move dependencies back into Pipfile and postpone versioning until we understand deployments with Kubernetes better.

**Pull request merged**
