### PR TITLE
Set allowed origins

### PR DESCRIPTION
**Pull request by kvikshaug**

### CODE REVIEW

**Comment by Midnighter** [comment]
Not sure why this is handled from a secret but maybe they are easier to establish platform-wide compared to environment variables?

**Comment by kvikshaug** [comment]
It's not really sensitive information, the idea is just that it can make a targeted attack more difficult by not having the information available. The secret is (currently) deployment specific, but yes, it could preferably 1) be a shared secret or 2) if not secret, a shared configmap. What do you prefer?

**Comment by Midnighter** [comment]
I think a shared configmap sounds good. We can easily create it from an env file (`key=value` pairs per line) and they can even be used directly in pod configurations.

Could you also add to the README that a `SECRET_KEY` should be created, please? Preferably from:
```
python -c "import os;print(os.urandom(512))" > secret.txt
```
(Not 100% sure what adequate key lengths are today.)

**Comment by kvikshaug** [comment]
I'll close this and add an issue for setting it from a configmap.

**Pull request closed without merging**
